require("core.plugins.telescope")
require("core.plugins.treesitter")
require("core.plugins.lsp")
require("core.plugins.completions")
require("core.plugins.formatting")
require("core.plugins.undotree")
